{
 "title": "Capstone WIFI",
 "time": { "from": "now-5m", "to": "now" },
 "refresh": "10s",
 "templating": {
  "list": [
   {
    "name": "Session",
    "query": "import \"influxdata/influxdb/schema\"\nschema.tagValues(bucket: \"WifiData\", tag: \"session_id\")"
   }
  ]
 },
 "panels": [
  {
   "title": "Uptime",
   "type": "stat",
   "gridPos": { "h": 6, "w": 3, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "from(bucket: \"WifiData\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"wifi_telemetry\")\r\n  |> filter(fn: (r) => r[\"session_id\"] == \"${Session}\")\r\n  |> filter(fn: (r) => r[\"_field\"] == \"uptime_seconds\")\r\n  |> keep(columns: [\"_time\", \"_value\"])"
    }
   ]
  },
  {
   "title": "CPU Temp",
   "type": "gauge",
   "gridPos": { "h": 6, "w": 3, "x": 3, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "celsius" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "from(bucket: \"WifiData\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"wifi_telemetry\")\r\n  |> filter(fn: (r) => r[\"session_id\"] == \"${Session}\")\r\n  |> filter(fn: (r) => r[\"_field\"] == \"cpu_temp_celsius\")\r\n  |> keep(columns: [\"_time\", \"_value\"])"
    }
   ]
  },
  {
   "title": "CPU Usage",
   "type": "gauge",
   "gridPos": { "h": 6, "w": 3, "x": 6, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "from(bucket: \"WifiData\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"wifi_telemetry\")\r\n  |> filter(fn: (r) => r[\"session_id\"] == \"${Session}\")\r\n  |> filter(fn: (r) => r[\"_field\"] == \"cpu_usage_percent\")\r\n  |> keep(columns: [\"_time\", \"_value\"])"
    }
   ]
  },
  {
   "title": "Ram Utilization",
   "type": "bargauge",
   "gridPos": { "h": 6, "w": 5, "x": 9, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "from(bucket: \"WifiData\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"wifi_telemetry\")\r\n  |> filter(fn: (r) => r[\"session_id\"] == \"${Session}\")\r\n  |> filter(fn: (r) => r[\"_field\"] == \"ram_usage_percent\")\r\n  |> keep(columns: [\"_time\", \"_value\"])"
    }
   ]
  },
  {
   "title": "Signal Strength",
   "type": "gauge",
   "gridPos": { "h": 6, "w": 5, "x": 14, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "dBm" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "from(bucket: \"WifiData\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"wifi_telemetry\")\r\n  |> filter(fn: (r) => r[\"session_id\"] == \"${Session}\")\r\n  |> filter(fn: (r) => r[\"_field\"] == \"signal_dbm\")\r\n  |> keep(columns: [\"_time\", \"_value\"])"
    }
   ]
  },
  {
   "title": "WiFi Quality",
   "type": "stat",
   "gridPos": { "h": 6, "w": 5, "x": 19, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "from(bucket: \"WifiData\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"wifi_telemetry\")\r\n  |> filter(fn: (r) => r[\"session_id\"] == \"${Session}\")\r\n  |> filter(fn: (r) => r[\"_field\"] == \"link_quality_percent\")\r\n  |> keep(columns: [\"_time\", \"_value\"])"
    }
   ]
  },
  {
   "title": "Latency",
   "type": "stat",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "from(bucket: \"WifiData\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"wifi_telemetry\")\r\n  |> filter(fn: (r) => r[\"session_id\"] == \"${Session}\")\r\n  |> filter(fn: (r) => r[\"_field\"] == \"latency_ms\")\r\n  |> keep(columns: [\"_time\", \"_value\"])"
    }
   ]
  },
  {
   "title": "DNS Time",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 6 },
   "targets": [
    {
     "query": "from(bucket: \"WifiData\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"wifi_telemetry\")\r\n  |> filter(fn: (r) => r[\"session_id\"] == \"${Session}\")\r\n  |> filter(fn: (r) => r[\"_field\"] == \"dns_ms\")\r\n  |> keep(columns: [\"_time\", \"_value\"])"
    }
   ]
  },
  {
   "title": "Wi-Fi Link Speed / Bitrate",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 13 },
   "fieldConfig": { "defaults": { "unit": "Mbits" } },
   "targets": [
    {
     "query": "from(bucket: \"WifiData\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"wifi_telemetry\")\r\n  |> filter(fn: (r) => r[\"session_id\"] == \"${Session}\")\r\n  |> filter(fn: (r) => r[\"_field\"] == \"bitrate_mbps\")\r\n  |> keep(columns: [\"_time\", \"_value\"])"
    }
   ]
  },
  {
   "title": "Inbound Throughput vs. Outbound",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 13 },
   "fieldConfig": { "defaults": { "unit": "KBs" } },
   "targets": [
    {
     "query": "from(bucket: \"WifiData\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"wifi_telemetry\")\r\n  |> filter(fn: (r) => r[\"session_id\"] == \"${Session}\")\r\n  |> filter(fn: (r) => r[\"_field\"] == \"throughput_in_kbps\")\r\n  |> map(fn: (r) => ({ r with _field: \"Download\" }))\r\n  |> keep(columns: [\"_time\", \"_field\", \"_value\"])"
    },
    {
     "query": "from(bucket: \"WifiData\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"wifi_telemetry\")\r\n  |> filter(fn: (r) => r[\"session_id\"] == \"${Session}\")\r\n  |> filter(fn: (r) => r[\"_field\"] == \"throughput_out_kbps\")\r\n  |> map(fn: (r) => ({ r with _value: r._value * -1.0, _field: \"Upload\" }))\r\n  |> keep(columns: [\"_time\", \"_field\", \"_value\"])"
    }
   ]
  }
 ]
}